# Copyright: 2022 fpliu
# License: GPL-2.0-or-later

name: Alpine

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-12

    strategy:
      fail-fast: false
      matrix:
        version: [318]

    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
      - uses: leleliu008/github-actions-vagrant@main
        with:
          mem: 2048
          box: generic/alpine${{ matrix.version }}
          log: debug
          run: |
            run id
            run pwd
            run export -p
            run apk update
            run apk add git
            touch aaa

      - run: printf '%s\n' "$VAGRANT_CWD"
      - run: scp -i $VAGRANT_CWD/.vagrant/machines/default/virtualbox/private_key -o StrictHostKeyChecking=no -r -P 2222 vagrant@127.0.0.1:/home/vagrant/leleliu008/github-actions-vagrant/aaa .
