# Copyright: 2022 fpliu
# License: GPL-2.0-or-later

name: OpenBSD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-12

    steps:
      - uses: leleliu008/github-actions-vagrant@v2
        with:
          mem: 2048
          box: generic/openbsd6
          log: debug
          run: |
            run ls

      - run: printf '%s\n' "$VAGRANT_CWD"
